### ISSUE TITLE
Master / Livox diffeerences

### ISSUE THREAD

**Issue by FPSychotic** [Huguet57/LIMO-Velo#33]
Hi, I can use the Livox branch or the master one with Velodyne, is there any advantage or improvements that master have over Livox branch, have they the same level of development?

Thanks

**Comment by Huguet57** [comment]
Actually for the LiVoX one, the changes should only be how the data is inputted. However, it seems that FAST-LIO does a better job with LiVoX overall.

The master branch is the most advanced + stable branch.
